query RandomQuestionQuery($offset: Int, $limit: Int) {
    randomQuestion(offset: $offset, limit: $limit) {
        id
        description
        answer
        status
        favorite_status
        gold
        ticket
        liked
        count_likes
        count_comments
        selections_array {
            Text
            Value
        }
        audio {
            id
            url
            name
            duration
        }
        image {
            id
            path
            width
            height
        }
        video {
            id
            url
            height
            width
            path
            rotate
            duration
            cover
        }
        category {
            id
            name
        }
        explanation {
            id
            content
            video {
                width
                height
                cover
                url
            }
            images {
                width
                path
            }
        }
        type
        correct_count
        count
        wrong_count
        user {
            id
            name
            avatar
            followers_count
            question_count
            roles
        }
        submit
        audits {
            id
            user {
                id
                name
                avatar
            }
            status
        }
    }
}
