# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'datizhuanqian' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for datizhuanqian

  

  platform :ios, '9.0'
  #pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'datizhuanqianTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'datizhuanqian-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for datizhuanqian-tvOS

  target 'datizhuanqian-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
